name: release
on:
  # the 1st condition
  release:
    branches: [master]
    types: [published]
jobs:
  docs:
    name: documentation
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: setup pandoc environment
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.0.1' # The pandoc version to download (if necessary) and use.

    - name: install dependencies
      run: |
        pip install -r requirements_dev.txt
        echo "# Test" | pandoc -t html

    - name: Build flit package and install dependencies
      run: |
        # install package using flit locally to run documentation notebooks
        flit build
        flit install --deps=develop --symlink

    - name: Build documentation and commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: ./docs
        requirements_path: ./requirements.txt
        target_branch: gh-pages
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages

  tests:
    name: pre-release tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: install dependencies
      run: |
        pip install -r requirements_dev.txt
        pip install -r requirements.txt
        pip install -e .

    - name: Build flit package and install dependencies
      run: |
        # install package using flit locally to run documentation notebooks
        flit build
        flit install --deps=develop --symlink

    - name: Run unit tests
      run: python -m pytest --import-mode=append tests/

  deploy_test:
    name: publish test PyPI
    needs: [docs,tests]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2


    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: install dependencies
      run: |
        pip install -r requirements_dev.txt
        pip install -r requirements.txt

    - name: Build and publish to TestPyPI
      run: |
        flit publish
      env:
        FLIT_INDEX_URL: https://test.pypi.org/legacy/
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

  deploy:
    name: publish PyPI
    needs: [docs,tests,deploy_test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2


    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: install dependencies
      run: |
        pip install -r requirements_dev.txt
        pip install -r requirements.txt

    - name: Build and publish to TestPyPI
      run: |
        flit publish
      env:
        FLIT_INDEX_URL: https://upload.pypi.org/legacy/
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
