name: tests_dev
on:
  push:
    branches: [ dev ]
    tags:
      - "v*"
  pull_request:
    branches: [ dev ]
    tags:
      - "v*"
    
jobs:
  test:
    name: tests_dev
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
        python -m pip install -r requirements.txt
        python -m pip install -e .

    - name: Build flit package and install dependencies
      run: |
        # install package using flit locally to run documentation notebooks
        flit build
        flit install --deps=develop --symlink

    - name: Run unit tests
      run: python -m pytest --import-mode=append tests/